- import_role: 
    name: ipr-cnrs.nftables
  vars:
    ansible_become: yes
    nft_define_host:
      output tcp accepted:
        name: out_tcp_accept
        value: '{ ssh, http, https, hkp, 8080 }'
      input tcp accepted:
        name: in_tcp_accept
        value: "{ ssh, http, https, 8080 }"
      input udp accepted:
        name: in_udp_accept
        value: "{ }"
      output udp accepted:
        name: out_udp_accept
        value: "{ bootps, domain, ntp }"
    nft_set_host:
      in_udp_accept:
        - type inet_service; flags interval;
        - elements = $in_udp_accept

    nft_main_conf_path: "/etc/nftables_part1.conf" 
    nft_service_unit_content: "files/nftables.service.j2" 
    nft_service_manage: no

- name: enable ipv4 ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: add nftables part 2
  template:
    src: 'files/nftables_part2.conf'
    dest: '/etc/nftables_part2.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: yes

- name: assemble nftables config from the two parts
  assemble:
    regexp: "nftables_part.*"
    src: '/etc'
    dest: '/etc/nftables.conf'
  notify: Restart nftables service

- name: install Debian systemd service unit
  template:
    src: 'files/nftables.service.j2'
    dest: '/lib/systemd/system/nftables.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: nftables__register_systemd_service
  notify: Restart nftables service

- name: always restart nftables because we don't sense all changes
  command: /bin/true
  notify: Restart nftables service
